[package]
name = "neuro-desktop"
version = "0.1.0"
edition = "2024"

[dependencies]
neuro-sama = "0.4.5"
rust-core = { path = "../../native/rust-core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"